dev:
  vpcid: "vpc-xxxx" #VPC ID where DataMasque being deployed
  db_subnetgroup: "db subnet group" #Name of the db subnet group to deploy RDS
  ingress_cidr: 10.x.x.x/x #CIDR range to allow connections to DataMasque application
  subnets: #Subnet IDs in the VPC
    subnetb: "subnet-0axxxx" #2b private subnet
    subnetc: "subnet-04xxxx" # 2c: private subnet
    subneta: "subnet-0axxxx" #2a: private subnet

prod:
  vpcid: "vpc-xxxx"
  db_subnetgroup: "db subnet group" #Name of the db subnet group to deploy RDS
  db_subnetgroup: private-db-subnetgroup
  ingress_cidr: 10.x.x.x/x
  subnets:
    subnetb: "subnet-0axxxx" #2b private subnet
    subnetc: "subnet-04xxxx" # 2c: private subnet
    subneta: "subnet-0axxxx" #2a: private subnet